Begin changing md5 to sha256
kubuntu-team/kubuntu-manual pull request #5
Opened 2022-01-15 20:28 UTC by marco-parillo

2022-01-15 20:46 UTC, ricktimmis commented on docs/installation.rst
>  Download it though `Get Kubuntu <http://www.kubuntu.org/getkubuntu/>`_.
Can we make this https

2022-01-15 20:46 UTC, ricktimmis commented on docs/installation.rst
> +    sha256 -r kubuntu-17.04-desktop-amd64.iso
Let's change this to 20.04

2022-01-15 20:48 UTC, ricktimmis requested changes
Made a few suggestions, this is a good start

2022-01-15 20:48 UTC, ricktimmis commented on docs/installation.rst
> +    sha256sum kubuntu-17.04-desktop-amd64.iso
Same here 20.04

2022-01-15 20:58 UTC, ahoneybun commented
@ricktimmis I made the changes that you requested so I think we're good for another review before merging.

2022-01-16 12:13 UTC, ricktimmis approved these changes
I checked the destination for the link, and it looks like a good place to put the user.
LGTM
Ship It!

2022-01-16 15:31 UTC, merged